---
- name: Create Python 3 symlink
  file:   
    src: "/usr/bin/python3"
    path: "/usr/bin/python"
    state: link

- name: Install pip3 tools
  apt:
    pkg:
      - python3-pip
      - build-essential
      - libssl-dev
      - libffi-dev
    update_cache: yes
